### ISSUE TITLE
Tracking Issue: reduce allocations during bulk data transfers

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3526]
A 1 GB transfer using v0.29.0 currently creates (as measured by pprof's alloc tool, which measures _total_ allocations over the lifetime of the process) about 500 - 600 MB of allocations, both on the sender and on the receiver side.

This is a problem for performance, because allocating memory consumes resources, and more importantly, all of this memory has to be garbage-collected, putting a lot of pressure on the GC.

We need to drastically reduce the amount of allocations. Target is a reduction of an order of magnitude.

The worst offenders at the moment seem to be:
- [x] allocations of `wire.{Extended}Header`. This is a struct representing a QUIC packet header
- [x] allocations of `ackhandler.Packet` structs (used to track sent packets until they're acknowledged / declared lost): #3525
- [x] allocations of `wire.AckFrame`: https://github.com/lucas-clemente/quic-go/pull/3547
- [x] parsing the control message via `unix.ParseSocketControlMessage`. This will require us to either rewrite that code ourselves, or upstream a fix to `golang.org/x/net` (both?)
     Go issue: https://github.com/golang/go/issues/54714
     PR: https://github.com/lucas-clemente/quic-go/pull/3609
- [x] use a more efficient type for connection IDs: #3527
- [x] stop using a `bytes.Buffer` when packing packets. Allocating new `bytes.Buffer`s is responsible 32 MB of allocations. We can just append to a `[]byte`
     #3530
- [x] don’t allocate a new `bytes.Reader` for every packet when parsing frames. This is responsible for 32 MB of allocations on the receiver side.
    #3536
- [x] list allocations, especially when sending packets: https://github.com/lucas-clemente/quic-go/pull/3655

### Server
![server](https://user-images.githubusercontent.com/1478487/187061914-e1842fb0-e981-442a-a536-8cfcd7bb07b1.png)

### Client
![profile001](https://user-images.githubusercontent.com/1478487/187061924-70fb2940-d6f3-4567-8524-42a7b47239dd.png)

**Comment by zllovesuki** [comment]
On `v0.30.0` the allocations look way better:
```
File: specter-linux-amd64
Type: alloc_space
Time: Oct 30, 2022 at 4:30am (PDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top5
Showing nodes accounting for 356.03MB, 51.02% of 697.81MB total
Dropped 309 nodes (cum <= 3.49MB)
Showing top 5 nodes out of 109
      flat  flat%   sum%        cum   cum%
  119.51MB 17.13% 17.13%   119.51MB 17.13%  github.com/lucas-clemente/quic-go.(*packetPacker).getShortHeader
   89.51MB 12.83% 29.95%    89.51MB 12.83%  golang.org/x/sys/unix.ParseSocketControlMessage
   69.50MB  9.96% 39.91%    95.51MB 13.69%  github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket
   49.50MB  7.09% 47.01%   159.52MB 22.86%  github.com/lucas-clemente/quic-go.(*oobConn).ReadPacket
      28MB  4.01% 51.02%       28MB  4.01%  kon.nect.sh/specter/chord.(*LocalNode).fixK
```

**Comment by marten-seemann** [comment]
Interesting article on how to reduce allocations using a `sync.Pool` in combination with finalizers.

**Comment by marten-seemann** [comment]
pprof update, running in a branch that includes the above PRs (#3644, #3646, #3648, #3655). Again, the scenario is the transfer of a single 1 GB file on a single stream.

## Server
![profile001](https://user-images.githubusercontent.com/1478487/210112862-38c74079-34fc-4aca-bad6-edf1ea8ee5f9.png)

We're down from 540 MB to 128 MB, that's 76%. 

## Client
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1478487/210112695-82b22883-bc53-4e68-b749-bc146883ed3b.png">

We're down from 514 MB to 147MB, that's 72%. I believe we can get rid of the allocation in `ReadPacket` as well, by using a `sync.Pool` for the `receivedPacket` struct.

**Comment by mholt** [comment]
Impressive work, Marten!!

**Comment by zllovesuki** [comment]
Do we know that allocation overhead (if any) for opening/closing streams? That would be common in the RPC use case

**Comment by marten-seemann** [comment]
> Do we know that allocation overhead (if any) for opening/closing streams? That would be common in the RPC use case

I just added a new benchmark test that opens and accepts streams in #3697. Looks like we're allocating almost 4 kB per stream:
```
goos: darwin
goarch: arm64
pkg: github.com/quic-go/quic-go/integrationtests/self
BenchmarkStreamChurn-10           561832              2662 ns/op            3696 B/op         42 allocs/op
```

**Comment by marten-seemann** [comment]
@zllovesuki If you have any ideas how to optimize that, I'd be happy to review a PR :)
