### ISSUE TITLE
optimize quic-go for short RTTs

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#4289]
There are a number of things that would need to be done to make quic-go work well on short (<20ms) RTTs:

- [ ] To avoid retransmissions during the handshake, handshake packets need to be acknowledged immediately. This is just fixing a bug, RFC 9002 already requires us to do so: #4279
- [ ] The `max_ack_delay` (25ms) is way too long for short RTTs, leading to sluggish loss recovery. We should be able to negotiate a shorter value. We'll need the ACK Frequency extension for that: #2482.
- [ ] Often times users know the expected RTT (e.g. when starting a transfer in a DC). It should be possible to configure the initial RTT to speed up the handshake: #3754.
